### ISSUE TITLE
UI for the Profile 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/StoryBook-RN#1]
### Tasks : 

The current UI only provides the feature to `Logout` from the `Profile Page`

**We need to design it!**

**Comment by SaiSravanthiChandana** [comment]
Kindly assign it to me

**Comment by pooranjoyb** [comment]
> Kindly assign it to me

Hey @SaiSravanthiChandana will assign this issue once JWOC 2024 phase 1 starts! 😄

**Comment by Sruti-sahini** [comment]
Hi @pooranjoyb please assign this issue to me. I am from JWoC 2024

**Comment by pooranjoyb** [comment]
> Hey @SaiSravanthiChandana will assign this issue once JWOC 2024 phase 1 starts! 😄 Don't forget to Star ⭐ the Repository :)))

Hey @Sruti-sahini  will assign this issue once JWOC 2024 phase 1 starts! 😄
Don't forget to Star ⭐ the Repository :)))

**Comment by AyushSinghbharti** [comment]
Hello @pooranjoyb I would like to contribute in this project, please assign this issue to me

**Comment by pooranjoyb** [comment]
> Hello @pooranjoyb I would like to contribute in this project, please assign this issue to me

Hey @AyushSinghbharti  will assign this issue once JWOC 2024 phase 1 starts! 😄
Don't forget to Star ⭐ the Repository :)))

**Comment by pooranjoyb** [comment]
Guys the first comment gets assigned! @AyushSinghbharti @Sruti-sahini @SaiSravanthiChandana
