### ISSUE TITLE
UI for the Stories Page 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/StoryBook-RN#15]
### Tasks : 

- Improve the UI of the Stories Page
- Use Glass UI (if possible)

### Screenshots : 

![image](https://github.com/pooranjoyb/StoryBook-RN/assets/90945182/05c59d5c-682d-45f4-8227-a30c2140111f)

**Comment by Hacxmr** [comment]
Hey ! @pooranjoyb  I am interested in working on this issue :)

**Comment by AyushSinghbharti** [comment]
sure, working on it!!!
