### ISSUE TITLE
Redesign a UI for stories List

### ISSUE THREAD

**Issue by AyushSinghbharti** [pooranjoyb/StoryBook-RN#16]
Things to do:

- Improve stories List screen UI
- Add functionalities like : Add to favourite Button
- Create a modal for to show all items in favoriate list

**Comment by AyushSinghbharti** [comment]
@pooranjoyb Have a look at this issue, is this issue is fine for #14 PR?

**Comment by pooranjoyb** [comment]
Works @AyushSinghbharti 🚀
