### ISSUE TITLE
Persistent State of User Authentication 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/StoryBook-RN#3]
### Tasks : 
Due to some reasons **User Auth data** does not persists after closing the application. Your work is to
- Check the `non-persist` branch and recreate the persistence of user data
- You can achieve this using `redux-persist` & `async-storage` libraries

**NOTE :** This feature was already implemented before. 
Please refer [here](https://github.com/pooranjoyb/StoryBook-RN/commit/45faec56a31eb2768b03127fbc5e0af1f1f80b60) 
The state of the repository should be in [this](https://github.com/pooranjoyb/StoryBook-RN/tree/58554571e9c9c06e4c31fcd0ac8569a962e702a9) state after the issue is resolved.

**Comment by Hrx4** [comment]
Hey @pooranjoyb   assign this issue to me under JWOC

**Comment by pooranjoyb** [comment]
> Hey @pooranjoyb   assign this issue to me under JWOC 
> 
> 

You are assigned @Hrx4 :rocket: 
Go ahead.
