### ISSUE TITLE
Redesign the UI for Stories List 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/StoryBook-RN#7]
### Tasks : 
- Create an account in the Application. 
- Make sure to create an appealing UI for the Stories List Page.

### NOTE : This issue is under `JWOC-2024`

**Comment by pooranjoyb** [comment]
@swetasingh8844 Assigned! Go ahead :rocket:

**Comment by AyushSinghbharti** [comment]
@pooranjoyb Please assign this issue to me.

**Comment by Hacxmr** [comment]
Hey @pooranjoyb I am interested to contribute to this issue. Kindly assign me this under JWOC'24

**Comment by pooranjoyb** [comment]
Assigned to @AyushSinghbharti
