### ISSUE TITLE
Add more fields in the `Signup Page`

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/StoryBook-RN#8]
### Tasks : 

- Add fields like Age, Bio, Full Name, Nickname
- Fields like interests, favorite genres can also be added.

For more information or queries ping in the discord channel :)

### NOTE : This issue is under `JWOC 2024`

**Comment by tsunami03** [comment]
Please assign me this issue , Also please give discord link, I have registered but didnt get

**Comment by Hacxmr** [comment]
Hey! @pooranjoyb I would like to work on this issue. Kindly assign me this issue under JWOC'24

**Comment by pooranjoyb** [comment]
Go for it @Hacxmr 🚀

**Comment by Hacxmr** [comment]
Sure! @pooranjoyb

**Comment by Hacxmr** [comment]
Hey! @pooranjoyb I have made a PR #13 . Can you review and suggest if there is any possible improvement needed

**Comment by Hacxmr** [comment]
Hey! @pooranjoyb I have made a PR #17
